name: Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up MSVC (Visual Studio)
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      run: choco install ninja

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -G Ninja `
          -DCMAKE_BUILD_TYPE=Release `
          -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld" `
          -DLLVM_USE_CRT_RELEASE=MT `
          -DLLVM_PTHREAD_LIBS="" `
          -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/install_dist" `
          ../llvm

    - name: Build and Install with Ninja
      run: |
        cd build
        $cpu_count = $env:NUMBER_OF_PROCESSORS
        ninja -j $cpu_count
        ninja install

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-toolchain-windows-all-targets
        path: ${{ github.workspace }}/install_dist/
